### ISSUE TITLE
Error when try to install

### ISSUE THREAD

**Issue by lesliechw** [ephraim/node-fprint#11]
Hi,

I get the following error when I try to run the install command (npm install node-red-contrib-fprint). What I did wrong? Please advice, thank you. Regards, Les:

```
pi@raspberrypi:~/.node-red $ npm install node-red-contrib-fprint

> node-fprint@0.0.9 install /home/pi/.node-red/node_modules/node-fprint
> node-gyp rebuild

Package libfprint was not found in the pkg-config search path.
Perhaps you should add the directory containing `libfprint.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libfprint' found
gyp: Call to 'pkg-config --libs libfprint' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-fprint
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-fprint@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-fprint@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-08-22T07_06_08_919Z-debug.log
```

**Comment by lesliechw** [comment]
Sorry wrong repo. Repost at https://github.com/ephraim/node-red-contrib-fprint/issues/2
